In [4]:
import kagglehub
from kagglehub import KaggleDatasetAdapter
import json
import pandas as pd

In [ ]:
df_business_raw = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "yelp-dataset/yelp-dataset",
    "yelp_academic_dataset_business.json",
    pandas_kwargs={"lines": True},
)

# only care about Santa Barbara for now
df_business = df_business_raw[df_business_raw["city"]== "Santa Barbara"].copy()

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.2).

In [ ]:
# the categories that we want to include

allowed_categories = set(
    pd.read_csv("../processed/categories.csv")["category"]
    .dropna()
    .str.strip()
)

len(allowed_categories)

33

In [10]:
category_boolean = df_business["categories"].fillna("").apply(
    lambda value: any(
        category.strip() in allowed_categories
        for category in value.split(",")
    )
)

category_boolean

0         False
26        False
85         True
91        False
120       False
          ...
150239    False
150264     True
150284    False
150290    False
150303    False
Name: categories, Length: 3829, dtype: bool

In [13]:
df_business = df_business.loc[category_boolean].copy()

In [14]:
df_business.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
85,IDtLPgUrqorrpqSLdfMhZQ,Helena Avenue Bakery,"131 Anacapa St, Ste C",Santa Barbara,CA,93101,34.414445,-119.690672,4.0,389,1,"{'RestaurantsTakeOut': 'True', 'NoiseLevel': '...","Food, Restaurants, Salad, Coffee & Tea, Breakf...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-14:0', '..."
141,SZU9c8V2GuREDN5KgyHFJw,Santa Barbara Shellfish Company,230 Stearns Wharf,Santa Barbara,CA,93101,34.408715,-119.685019,4.0,2404,1,"{'OutdoorSeating': 'True', 'RestaurantsAttire'...","Live/Raw Food, Restaurants, Seafood, Beer Bar,...","{'Monday': '0:0-0:0', 'Tuesday': '11:0-21:0', ..."
691,-kY_HDP7IMvGl-kBIZVU4A,Dune Coffee Roasters - Anacapa,528 Anacapa St,Santa Barbara,CA,93101,34.418994,-119.695068,4.0,320,1,"{'RestaurantsPriceRange2': '2', 'BusinessAccep...","Coffee & Tea, Coffee Roasteries, Food","{'Monday': '6:0-17:0', 'Tuesday': '6:0-17:0', ..."
946,-ujBP1Dw0j1-Ffaz97-LXQ,Lama Dog Tap Room,116 Santa Barbara St,Santa Barbara,CA,93101,34.415747,-119.688480,4.0,238,1,"{'RestaurantsReservations': 'False', 'WiFi': '...","Beer, Wine & Spirits, Pubs, Arts & Entertainme...","{'Monday': '0:0-0:0', 'Tuesday': '11:30-17:0',..."
1320,UFpCraqzFBAhtZqmxmiWsA,Cat Therapy,"1213 State St, Ste L",Santa Barbara,CA,93101,34.423302,-119.705471,4.5,116,1,"{'WheelchairAccessible': 'True', 'WiFi': 'u'fr...","Themed Cafes, Cafes, Pets, Arts & Entertainmen...","{'Monday': '10:0-17:15', 'Wednesday': '10:0-19..."

In [17]:
df_business[df_business["business_id"] == "UFpCraqzFBAhtZqmxmiWsA"].T

                                                           1320
business_id                              UFpCraqzFBAhtZqmxmiWsA
name                                                Cat Therapy
address                                    1213 State St, Ste L
city                                              Santa Barbara
state                                                        CA
postal_code                                               93101
latitude                                              34.423302
longitude                                           -119.705471
stars                                                       4.5
review_count                                                116
is_open                                                       1
attributes    {'WheelchairAccessible': 'True', 'WiFi': 'u'fr...
categories    Themed Cafes, Cafes, Pets, Arts & Entertainmen...
hours         {'Monday': '10:0-17:15', 'Wednesday': '10:0-19...

In [ ]:
df_reviews = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "yelp-dataset/yelp-dataset",
    "yelp_academic_dataset_review.json")

In [ ]:
df_reviews.shape

(1000, 9)